services:
  web:
    build: 
      context: .\setup\apache\
      args:
        - HTTPD_VERSION=${HTTPD_VERSION:-2.4.57}

    container_name: httpd
    volumes:
      - .\public\:/usr/local/apache2/htdocs/
    ports:
      - "${HTTPD_HOST_SIDE_PORT:-8080}:80"
    
    depends_on:
      - php

  php:
    build:
      context: .\setup\php\
      args:
        - PHP_VERSION=${PHP_VERSION:-8.2.7}
    container_name: php
    volumes:
      - .\public\:/usr/local/apache2/htdocs/